---
title: "adv_eda"
format: html
---

```{r}
library(tidyverse)
library(arrow)
library(gemstools)
library(plotly)

source("./bin_timeseries.R")
```

```{r}
ds <- open_dataset("data/processed/lander/adv_data_.parquet")
bad_times <- read_csv("data/2025_Hadleys_Harbor/gems_2025_bad_data_periods.csv")
```

```{r}
names(ds)
```

```{r}
df_binned <- ds |> 
  filter(corr1 > 60,
         corr2 > 60,
         corr3 > 60) |> 
  select(timestamp, pressure, u, v, w) |> 
  collect() |> 
  bin_timeseries(
    datetime_col = "timestamp",
    value_cols = c("pressure",
                   "u",
                   "v",
                   "w"
    )
  ) |> 
  mutate(
    cur_speed = sqrt(v^2 + u^2),
    cur_dir = atan2(u, v) * (180 / pi)
  )
```

```{r}
p <- ggplot(df_binned, aes(bin_time, pressure)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

```{r}
p <- ggplot(df_binned, aes(bin_time, cur_speed)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

```{r}
p <- ggplot(df_binned, aes(bin_time, cur_dir)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

```{r}
p <- ggplot(df_binned, aes(bin_time, w)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

```{r}
lander_moves <- read_csv("data/2025_Hadleys_Harbor/gems_lander_move_times.csv") |> 
  rename(change_timestamp = timestamp) |> 
  mutate(lander_position = row_number())

df_binned_mv <- df_binned |> 
  arrange(bin_time) |> 
  left_join(lander_moves,
            by = join_by(closest(bin_time > change_timestamp))) |> 
  fill(lander_position, .direction = "down") |> 
  mutate(lander_position = replace_na(lander_position, 1)) |> 
  select(-change_timestamp)
```


```{r}
df_bin_rot <- df_binned_mv |> 
  group_by(lander_position) |>
  nest() %>%
  mutate(data = map(data, ~rotate_to_minimize_z(.x, "u", "v", "w"))) %>%
  unnest(data) %>%
  ungroup()
```

```{r}
p <- ggplot(df_bin_rot, aes(bin_time, w_rot)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```
