---
title: "GEMS Calibration"
format: html
---

```{r}
library(tidyverse)
library(gemstools)
library(patchwork)
library(plotly)
```

ProOceanus

```{r}
co2_df <- read_prooceanus("data/2025_Hadleys_Harbor/prooceanus/prooceanus_co2_gems_hadley_2025-08-19.txt")

co2_df_res <- co2_df |> 
  filter(ts >= as.Date("2025-07-17 20:50:00"),
         ts <= as.Date("2025-08-03")) |> 
  mutate(ts = floor_date(ts, unit = "10 mins")) |>
  group_by(ts) |>
  summarize(co2 = mean(co2, na.rm = TRUE))

co2p <- ggplot(co2_df_res, aes(x =ts, y = co2)) +
  #geom_point() +
  geom_line() +
  labs(
    title = "ProOceanus CO2 Data",
    x = "Date",
    y = "CO2 (ppm)"
  ) +
  theme_minimal()

ggplotly(co2p)
```

seaphox

```{r}
seaphox_df <- data.table::fread("data/2025_Hadleys_Harbor/seaphox/Shallow SeapHox2-0000453-Data-20250716T200119.csv") |> 
  janitor::clean_names() |> 
  mutate(timestamp = lubridate::mdy_hms(date_time_utc_00_00,
                          tz = "UTC")) |>
  select(timestamp,
           pH = internal_p_h_p_h,
           temp = p_h_temperature_celsius,
           pressure = pressure_decibar,
           sal = salinity_psu,
           oxygen = oxygen_ml_l) |> 
  filter(timestamp > "2025-06-25 20:00:00",
         timestamp <= "2025-07-16 14:00:00")
         
```

```{r}
spt <- seaphox_df |> 
  ggplot(aes(x = timestamp, y = temp)) +
  geom_line() +
  labs(
    title = "SeapHOx",
    x = "Date",
    y = "Temperature (°C)"
  ) +
  theme_minimal()
sps <- seaphox_df |> 
  ggplot(aes(x = timestamp, y = sal)) +
  geom_line() +
  labs(
    title = "SeapHOx",
    x = "Date",
    y = "salinity (psu)"
  ) +
  theme_minimal()
spp <- seaphox_df |> 
  ggplot(aes(x = timestamp, y = pH)) +
  geom_line() +
  labs(
    title = "SeapHOx",
    x = "Date",
    y = "pH"
  )
subplot(ggplotly(spt), ggplotly(sps), ggplotly(spp), nrows = 3, shareX = TRUE, titleY = TRUE)
```

```{r}
p <- seaphox_df |> 
  ggplot(aes(x = timestamp, y = oxygen)) +
  geom_line() +
  labs(
    title = "SeapHOx",
    x = "Date",
    y = "Oxygen [ml/l]"
  ) +
  theme_minimal()
ggplotly(p)
```

Sept SeapHOx

```{r}
seaphox_df <- data.table::fread("data/2025_Hadleys_Harbor/seaphox/Shallow SeapHox2-0000453-Data-20250916T181837.csv") |> 
  janitor::clean_names() |> 
  mutate(timestamp = lubridate::mdy_hms(date_time_utc_00_00,
                          tz = "UTC")) |>
  select(timestamp,
           pH = internal_p_h_p_h,
           temp = p_h_temperature_celsius,
           pressure = pressure_decibar,
           sal = salinity_psu,
           oxygen = oxygen_ml_l) |> 
  filter(timestamp > "2025-09-11 14:15:00",
         timestamp <= "2025-09-16 11:00:00")
         
```

```{r}
spt <- seaphox_df |> 
  ggplot(aes(x = timestamp, y = temp)) +
  geom_line() +
  labs(
    title = "SeapHOx",
    x = "Date",
    y = "Temperature (°C)"
  ) +
  theme_minimal()
sps <- seaphox_df |> 
  ggplot(aes(x = timestamp, y = sal)) +
  geom_line() +
  labs(
    title = "SeapHOx",
    x = "Date",
    y = "salinity (psu)"
  ) +
  theme_minimal()
spp <- seaphox_df |> 
  ggplot(aes(x = timestamp, y = pH)) +
  geom_line() +
  labs(
    title = "SeapHOx",
    x = "Date",
    y = "pH"
  )
subplot(ggplotly(spt), ggplotly(sps), ggplotly(spp), 
        nrows = 3, shareX = TRUE, titleY = TRUE)
```

```{r}
p <- seaphox_df |> 
  ggplot(aes(x = timestamp, y = oxygen)) +
  geom_line() +
  labs(
    title = "SeapHOx",
    x = "Date",
    y = "Oxygen [ml/l]"
  ) +
  theme_minimal()
ggplotly(p)
```
