---
title: "rga eda"
format: html
---

```{r}
library(tidyverse)
library(arrow)
library(plotly)
library(gemstools)


source("bin_timeseries.R")
```

```{r}
df <- open_dataset("data/processed/landergems_rga/rga.parquet")
bad_times <- read_csv("data/2025_Hadleys_Harbor/gems_2025_bad_data_periods.csv")
```


```{r}
df_wide <- df |> 
  collect() |> 
  process_rga_to_wide()
```

Remove bad data periods and normalize by argon

```{r}
df_wide_cl <- df_wide |> 
  anti_join(bad_times, by = join_by(timestamp >= start_time, timestamp <= end_time)) |>
  mutate(
    across(starts_with("mass_"), ~ .x / mass_40, .names = "{.col}_40")
  )
```


```{r}
df_binned <- bin_timeseries(
  df_wide_cl,
  datetime_col = "timestamp",
  value_cols = c(
    "mass_15_40",
    "mass_28_40",
    "mass_32_40",
    "mass_44_40"
  )
)
    
```

```{r}
e <- ggplot(df_binned, aes(bin_time, mass_32_40, color = inlet)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```

```{r}
e <- ggplot(df_binned, aes(bin_time, mass_44_40, color = inlet)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```

Make one row for each high-low pair

```{r}
df_binned_wide <- df_binned |>
  group_by(grp = cumsum(inlet == "high")) |>
  mutate(mean_timestamp = mean(bin_time)) |>
  ungroup() |>
  pivot_wider(
    id_cols = c(grp, mean_timestamp),
    names_from = inlet,
    values_from = starts_with("mass_"),
    names_sep = "_"
  ) |>
  select(-grp) |>
  mutate(
    timestamp = lubridate::round_date(mean_timestamp, unit = "15 minutes"),
    across(ends_with("_high"), 
             \(x) (x + get(sub("_high$", "_low", cur_column()))) / 2, 
             .names = "{.col}_mean"),
    across(ends_with("_high"), 
             \(x) x - get(sub("_high$", "_low", cur_column())), 
             .names = "{.col}_diff"),
  ) |> 
  dplyr::relocate(timestamp, .before = dplyr::everything())
```


Difference plots

```{r}
e <- ggplot(df_binned_wide, aes(timestamp, mass_32_40_high_diff)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```

```{r}
e <- ggplot(df_binned_wide, aes(timestamp, mass_44_40_high_diff)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```


# calibration

## oxygen

read seaphox data, aggregate to 15 min avg and fit to GEMS data

TODO: add september seaphox

```{r}

seaphox_df <- data.table::fread("data/2025_Hadleys_Harbor/seaphox/Shallow SeapHox2-0000453-Data-20250716T200119.csv") |> 
  janitor::clean_names() |> 
  mutate(timestamp = lubridate::mdy_hms(date_time_utc_00_00,
                          tz = "UTC")) |>
  select(timestamp,
           pH = internal_p_h_p_h,
           temp = p_h_temperature_celsius,
           pressure = pressure_decibar,
           sal = salinity_psu,
           oxygen = oxygen_ml_l) |> 
  filter(timestamp > "2025-07-12 00:00:00",
         timestamp <= "2025-07-16 14:00:00")
         
```

```{r}
ggplot(seaphox_df, aes(timestamp, oxygen)) +
  geom_line()
```

```{r}
 # aggregate seaphox to nearest minute
  sp_m <- seaphox_df %>%
    mutate(timestamp = lubridate::floor_date(timestamp, "15 minute")) |>
    dplyr::group_by(timestamp) |>
    dplyr::summarise(seaphox_oxy = mean(oxygen))

  joined_data <- dplyr::inner_join(sp_m, df_binned_wide, by = dplyr::join_by(timestamp))

  o2_lm <- lm(seaphox_oxy ~ mass_32_40_high_mean, data = joined_data)
  coef(o2_lm)
```

```{r}
joined_data |>
  pivot_longer(
    cols = c(seaphox_oxy, mass_32_40_high_mean),
    names_to = "source",
    values_to = "value"
  ) |>  ggplot(aes(timestamp, value, color = source)) +
  geom_line()

```


fit oxygen

```{r}
ox_i = coef(o2_lm)[1]
ox_m = coef(o2_lm)[2]
df_binned_wide <- df_binned_wide |> 
  mutate(oxygen_high = ox_i + ox_m * mass_32_40_high,
         oxygen_low = ox_i + ox_m * mass_32_40_low)
```

```{r}
e <- df_binned_wide |>
  select(timestamp, oxygen_high, oxygen_low) |> 
  pivot_longer(
    cols = c(oxygen_high, oxygen_low),
    names_to = "inlet",
    values_to = "oxygen") |> 
    ggplot(aes(timestamp, oxygen, color = inlet)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```

## Carbon dioxide

```{r}
co2_df <- read_prooceanus("data/2025_Hadleys_Harbor/prooceanus/prooceanus_co2_gems_hadley_2025-08-19.txt")

co2_df_res <- co2_df |> 
  filter(ts >= as.Date("2025-07-17 20:50:00"),
         ts <= as.Date("2025-08-03")) |> 
  mutate(ts = floor_date(ts, unit = "15 mins")) |>
  group_by(ts) |>
  summarize(co2 = mean(co2, na.rm = TRUE))
```


```{r}
co2p <- ggplot(co2_df_res, aes(x =ts, y = co2)) +
  #geom_point() +
  geom_line() +
  labs(
    title = "ProOceanus CO2 Data",
    x = "Date",
    y = "CO2 (ppm)"
  ) +
  theme_minimal()

ggplotly(co2p)
```


```{r}
co2_df_res <- co2_df_res |> 
  rename(timestamp = ts,
         prooceanus_co2 = co2)

co2_j <- dplyr::inner_join(co2_df_res, df_binned_wide, by = dplyr::join_by(timestamp))

co2_lm <- lm(prooceanus_co2 ~ mass_44_40_high_mean, data = co2_j)
coef(co2_lm)
```

fit CO2

```{r}
co2_i = coef(co2_lm)[1]
co2_m = coef(co2_lm)[2]
df_binned_wide <- df_binned_wide |> 
  mutate(co2_high = co2_i + co2_m * mass_44_40_high,
         co2_low = co2_i + co2_m * mass_44_40_low)
```

```{r}
e <- df_binned_wide |>
  select(timestamp, co2_high, co2_low) |> 
  pivot_longer(
    cols = c(co2_high, co2_low),
    names_to = "inlet",
    values_to = "co2") |> 
    ggplot(aes(timestamp, co2, color = inlet)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```