---
title: "adv_eda"
format: html
---

```{r}
library(tidyverse)
library(arrow)
library(gemstools)
library(plotly)
library(targets)

tar_load(c(adv_file, adv_matlab_input))
```

# Initial plots of ADV data

```{r}
p <- ggplot(adv_matlab_input, aes(bin_time, pressure)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

```{r}
p <- ggplot(adv_matlab_input, aes(bin_time, cur_speed)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

```{r}
p <- ggplot(adv_matlab_input, aes(bin_time, cur_dir)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

```{r}
p <- ggplot(adv_matlab_input, aes(bin_time, w_rot)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

# Determine ADV rotations by lander position

Rotation angles for each lander position. 
These must be added manually in eddyflux_batch.m.

```{r}
# TODO: generated non-averaged ADV dataset from raw file here
# df_binned_mv |>
#   group_by(lander_position) |>
#   nest() |>
#   mutate(data = map(data, \(x) rotate_to_minimize_z(x, "u", "v", "w")$phi)) |>
#   unnest(data) |>
#   ungroup()
```

# Velocities

Horizontal current speed

```{r}
p <- ggplot(adv_matlab_input, aes(bin_time, cur_speed)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

Vertical current speed

```{r}
p <- ggplot(adv_matlab_input, aes(bin_time, w_rot)) +
  geom_line()

ggplotly(p, dynamicTicks = TRUE)
```

ADV velocities

```{r}
ggplotly(tar_read(adv_velocity_plot))
```


tide height vs horizontal velocity

```{r}
p <- ggplot(adv_matlab_input, aes(pressure, cur_speed)) +
  geom_smooth() +
  geom_point(alpha = 0.1)
p
```