---
title: "rga eda"
format: html
---

```{r}
library(tidyverse)
library(arrow)
library(plotly)
library(gemstools)
library(suntools)
library(patchwork)

```

Oxygen/Argon, colored by inlet

```{r}
e <- ggplot(df_binned, aes(bin_time, mass_32_40, color = inlet)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```

## Gradient plots

TODO: check for gradient in CH4 and H2S (None seen initially)

```{r}
e <- ggplot(df_binned_wide, aes(timestamp, mass_32_40_high_diff)) +
  geom_line()

f <- ggplot(df_binned_wide, aes(timestamp, par)) +
  geom_line()

# Convert to interactive plotly
p1_pl <- ggplotly(e, dynamicTicks = TRUE)
p2_pl <- ggplotly(f, dynamicTicks = TRUE)

subplot(p1_pl, p2_pl, nrows = 2, shareX = TRUE, titleY = TRUE, heights = c(0.5, 0.5))
```

```{r}
e <- ggplot(df_binned_wide, aes(timestamp, mass_44_40_high_diff)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```


# calibration

## oxygen



```{r}
ggplot(seaphox_df_jul, aes(timestamp, oxygen)) +
  geom_line()
```

```{r}
ggplot(seaphox_df_jul, aes(timestamp, sal)) +
  geom_line()
```

### September deployment

TODO: add september seaphox to cal

```{r}
ggplot(seaphox_df_sep, aes(timestamp, oxygen)) +
  geom_line()
```

Compare calibrated oxygen to seaphox oxygen

```{r}
joined_data |>
  pivot_longer(
    cols = c(seaphox_oxy, mass_32_40_high_mean),
    names_to = "source",
    values_to = "value"
  ) |>  ggplot(aes(timestamp, value, color = source)) +
  geom_line()

```


```{r}
e <- df_binned_wide |>
  select(timestamp, oxygen_high, oxygen_low) |> 
  pivot_longer(
    cols = c(oxygen_high, oxygen_low),
    names_to = "inlet",
    values_to = "oxygen") |> 
    ggplot(aes(timestamp, oxygen, color = inlet)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```

## Carbon dioxide


```{r}
tar_load(proco2_df_jul)
co2p <- ggplot(proco2_df_jul, aes(x =ts, y = co2)) +
  #geom_point() +
  geom_line() +
  labs(
    title = "ProOceanus CO2 Data",
    x = "Date",
    y = "CO2 (ppm)"
  ) +
  theme_minimal()

ggplotly(co2p)
```


```{r}
e <- df_binned_wide |>
  select(timestamp, co2_high, co2_low) |> 
  pivot_longer(
    cols = c(co2_high, co2_low),
    names_to = "inlet",
    values_to = "co2") |> 
    ggplot(aes(timestamp, co2, color = inlet)) +
  geom_line()

p <- ggplotly(e, dynamicTicks = TRUE)
p
```

Compare O2 and CO2 differences

```{r}
df_p <- df_binned_wide |> 
  mutate(
    ox = oxygen_low - oxygen_high,
    co2 = co2_low - co2_high) |> 
  select(timestamp, ox, co2)

ox_p <- ggplot(df_p, aes(timestamp, ox)) +
  geom_line() +
  labs(
    #title = "Oxygen Difference (Low - High)",
    x = "Timestamp",
    y = "Oxygen Difference (ml/L)"
  ) +
  theme_minimal()

co2_p <- ggplot(df_p, aes(timestamp, co2)) +
  geom_line() +
  labs(
    #title = "CO2 Difference (Low - High)",
    x = "Timestamp",
    y = "CO2 Difference (ppm)"
  ) +
  theme_minimal()

par_p <- ggplot(df_binned_wide, aes(timestamp, par)) +
  geom_line() +
  labs(
    #title = "Predicted PAR",
    x = "Timestamp",
    y = "PAR (µmol/m²/s)"
  ) +
  theme_minimal()

ox_ply <- ggplotly(ox_p, dynamicTicks = TRUE)
co2_ply <- ggplotly(co2_p, dynamicTicks = TRUE)
par_ply <- ggplotly(par_p, dynamicTicks = TRUE)

subplot(ox_ply, co2_ply, par_ply, nrows = 3, shareX = TRUE, titleY = TRUE, heights = c(0.4, 0.4, 0.2))
```

```{r}
df_p <- df_all |> 
  mutate(
    ox = oxygen_low - oxygen_high,
    co2 = co2_low - co2_high) |> 
  select(timestamp, ox, co2, par, cur_speed, cur_dir, w)

ox_p <- ggplot(df_p, aes(timestamp, ox)) +
  geom_line() +
  labs(
    #title = "Oxygen Difference (Low - High)",
    x = "Timestamp",
    y = "Oxygen Difference (ml/L)"
  ) +
  theme_minimal()

co2_p <- ggplot(df_p, aes(timestamp, co2)) +
  geom_line() +
  labs(
    #title = "CO2 Difference (Low - High)",
    x = "Timestamp",
    y = "CO2 Difference (ppm)"
  ) +
  theme_minimal()

cur_p <- ggplot(df_p, aes(timestamp, cur_speed)) +
  geom_line() +
  labs(
    #title = "Predicted PAR",
    x = "Timestamp",
    y = "Horizontal speed"
  ) +
  theme_minimal()

dir_p <- ggplot(df_p, aes(timestamp, cur_dir)) +
  geom_line() +
  labs(
    #title = "Predicted PAR",
    x = "Timestamp",
    y = "Horizontal dir"
  ) +
  theme_minimal()

par_p <- ggplot(df_p, aes(timestamp, par)) +
  geom_line() +
  labs(
    #title = "Predicted PAR",
    x = "Timestamp",
    y = "PAR (µmol/m²/s)"
  ) +
  theme_minimal()

ox_ply <- ggplotly(ox_p, dynamicTicks = TRUE)
co2_ply <- ggplotly(co2_p, dynamicTicks = TRUE)
cur_ply <- ggplotly(cur_p, dynamicTicks = TRUE)
dir_ply <- ggplotly(dir_p, dynamicTicks = TRUE)
par_ply <- ggplotly(par_p, dynamicTicks = TRUE)

subplot(ox_ply, co2_ply, cur_ply, dir_ply, par_ply,
        nrows = 5, shareX = TRUE, titleY = TRUE
)
```

