---
title: "GEMS NSF Final Report"
format:
  html:
    embed-resources: true
  docx:
    fig-dpi: 300
    reference-doc: custom-reference-doc.docx
  # pdf: default
echo: false
---

# GEMS Methods

## System overview

The gradient exchange mass spectrometry (GEMS) system combines a quadrupole mass spectrometer (QMS) sampling seawater from vertically spaced high and low inlets with an acoustic doppler velocimeter (ADV) to measure the current velocity between the inlets. The measurement system is deployed as a benthic lander. A surface barge provides power and data connections via a tether. Telemetry is provided via a GSM cellular data connection. Data acquisition, system control, and telemetry are handled by microcontrollers in the lander and barge and data is duplicated at both locations. The barge uses a wind turbine and solar panels for power generation.

The 1.8 m x 1.8 m surface support barge is constructed using commercial dock floatation supporting a welded aluminum frame with solar panel and wind turbine supports. A centrally positioned watertight box holds the 200AH battery, charge controller (Victron BlueSolar MPPT 150/35), and electronics for control and communication. The barge is moored using two anchors set in opposition to maintain position and orientation. Power is provided by two 200 W South-oriented solar panels and a wind generator (Air X Air30) producing 100 W at 8 m s^-1^ wind velocity, feeding power through a charge controller to a 24 V, 200 Ah LiFePO~4~ battery. The power system provided ample power for the lander and surface systems for the duration of the deployment. Control, data, and communication is handled by a microcontroller with custom firmware (Teensy 4.1) in the surface electronics box. Commands and data between barge and lander use the UDP protocol over 100baseT wired ethernet, and time correction, GPS position, and GSM telemetry are provided via a serial connection to a GSM/GPS module.

Data is transmitted and received via a GSM network connection. The main surface microcontroller exchanges commands and data with a paired microcontroller and GSM module with custom firmware (Amtel AT21 and SIM7600 in a Maduino Zero module). The system is programmed to send the last 500 lines (~60 s) of ADV and QMS data and receive commands every 10 minutes. This connection enables real-time visualization of system data for remote troubleshooting and maintenance visit planning.

The lander consists of an aluminum frame with mounts for the QMS, ADV, and valve control housings, and mounts for the inlets and ADV transducer. The QMS system and control electronics are housed in a 20 cm diameter, 90 cm long schedule 80 PVC tube with power and data connections for the ADV, valve housing, and surface barge. A second microcontroller (Teensy 4.1) controls data acquisition from the ADV and QMS via serial connections, logs data on a microSD card, and communicates with the surface using wired ethernet. A 10 m power and data cable connects the lander to the barge. 

Seawater from the high and low inlets is selected for measurement using a servo-controlled 3-way valve. A small PVC diversion valve (McMaster Carr \#4757K51) is mated to an underwater servo (Blue Trail SER-2020) using a custom PLA frame and adaptor. Actuation and timing is controlled using a microcontroller, which also records pump current draw to assess restrictions in flow due to biofouling. The controller and power system is mounted in a 10 by 30 cm watertight housing. Inlets were positioned 20 and 122 cm above the seabed. The top and bottom inlets were sampled for 7.5 minutes each, alternating continuously through the experiment.

Velocity is sampled at 8 Hz using a Nortek Vector ADV. The adv was mounted at 60 cm above the seabed between the gradient inlets. Signal amplitude and correlation are used to assess data quality.

The QMS system is a Stanford Research Systems RGA-100, configured as a Membrane Inlet Mass Spectrometer (MIMS). The system is based on an underwater quadrupole mass spectrometer design developed in part by Co-PI Wankel (Wankel et al., 2010; Wankel et al., 2011). A vacuum chamber containing the QMS is maintained at roughly 1E^-6^ Torr using a small turbomolecular pump (Pfeiffer HiPace 30) with a miniature scroll pump (Scroll Labs SVF-2) for rough vacuum. Seawater dissolved gas is introduced to the system via a flat, gas-permeable, Teflon AF2400 membrane mounted on PVDF. Seawater is continuously pushed across the membrane surface using a seabird SBE-5T pump with a flow rate of approximately 3 L min^-1^. The QMS is set to sample a range of masses with a long dwell time per mass to increase accuracy and reduce noise, resulting in an acquisition rate of approximately 1 second per mass. Masses measured were 14, 15, 18, 28, 32, 33, 34, 40, and 44, meaning each mass was sampled every 10 seconds.

## Description of the deployment

The system was deployed from June to October 2025. Initial deployment was planned for early June, but was delayed by an intermittent issue with cooling in the surface electronics enclosure, which was solved by a combination of solar reflective paint and addition of a sunshade. The system was deployed at 41.517 N, 70.701 W in a healthy eelgrass bed along the East shore of Uncatena Island in Hadleys Harbor. The harbor opens to the Northeast, facing Woods Hole, a passage with strong (\> 2 m s^-1^) tidal currents. Prevailing wind direction during the deployment was Southwest. The lander was placed in 2 m depth at mean low water and the tidal range is roughly 1.5 m. The lander was oriented such that the intakes and ADV transceiver were exposed to the mean current direction and not occluded by the lander systems. The barge was moored 4 m West of the lander using two anchors in opposition to limit movement due to tide and current, and to maintain Southerly orientation of the solar panels. The site was visited roughly weekly during the deployment for cleaning, sampling, and maintenance. 

Co-deployments of calibrated sensors and discrete sampling were used for calibration of the QMS partial pressures for masses with measurable variability and gradient. Two week-long deployments of a Seabird SeapHOx were used to measure Oxygen, and a single two-week deployment of a Pro-Oceanus CO2-Pro was used to measure CO~2~. The SeapHOx  was deployed on the seabed 2 m upcurrent of the GEMS lander, and the CO2-Pro was deployed below the barge, 4 m from the lander. Discrete samples for methane and hydrogen sulfide concentration were taken once before establishing that concentrations and variability were too small to quantify with the QMS data. Methane samples were taken in gas-tight 60 ml syringes and analysed using GC-FID on an Agilent-6890 gas chromatograph. Methane concentration at the lower inlet was 20 μmol L^-1^. Hydrogen sulfide samples were taken in gas-tight syringes at the low inlet, fixed as ZnS by addition of zinc acetate and analyzed by the methylene blue technique (Cline, 1969). Total sulfide concentration was below the limit of detection for this method.

Eelgrass growth samples were taken at the site roughly monthly during the deployment period, continuing a sampling series started at the site in 2023. Eelgrass shoots, epiphites, and algae were sampled from 3-5 20 cm square quadrats, randomly distributed within 15 m of the GEMS lander. Shoots were counted and measured, then shoots, algae, and epiphytes were dried at 60 C and weighed for biomass assessment.

The deployment was generally successful, but several issues resulted in planned and unplanned maintenance. In the coastal environment, fouling was a constant concern. Growth of algae on the upper and lower inlet screens and on the QMS inlet membrane altered the flow and pressure of water across the inlet, which in turn affected gas transport across the membrane. This was visible in QMS telemetry data as a reduction in partial pressure of gas species; this reduction was used as a diagnostic for site visits to clean the system. The QMS was generally reliable, but the system did shut down unexpectedly 24 h after a lander maintenance due to high QMS filament current triggering an interlock. This was likely due to the release of a small pocket of gas within the system after the initial evacuation and restart of the system after maintenance. After the event, the system was restarted remotely using the GSM communication system. Another unplanned breakdown was caused by the failure of an undersized DC-DC converter which supplied 12 V power to the valve and ADV modules. High current loads during valve movement caused the converter to fail to a state where 24 V was passed to the ADV and valve, resulting in issues with the valve and ADV. The inlet selector valve had several failures due to repeated actuations causing fatigue in a splined joint in the valve body. The valve was an off-the-shelf commercial 3-way fluid handling unit made from PVC. No test data were available from the manufacturer, but the valve was clearly not designed for continuous use. The valve failed repeatedly after roughly 5000 actuations. Our solution was to treat it as a field-replaceable part for the duration of the deployment, but a more durable valve and a gentle acceleration profile for the servo actuator are necessary to avoid future valve failures. 

## Data reduction

Mass spectrometry, velocity, and ancillary data are stored in a single file, rotated every 6 hours. A data reduction package was developed in the R language to validate and parse GEMS file data, normalize and calibrate QMS mass data, use velocity data to model eddy transport, and calculate fluxes using the gradient method. 

QMS mass data was normalized to Argon (mass 40) to reduce the effects of flow, pressure and temperature on gas solubility and QMS signal. A pronounced effect due to inlet biofouling was observed in raw mass signals; this was greatly reduced by normalizing the signals to Argon. Argon normalization also removes physical effects on gas concentration (temperature, air-sea exchange), leaving only biological signals.

Data from co-deployed sensors and concurrent sampling were used for calibration of the QMS signals. A linear model between the Argon-normalized oxygen and CO~2~ signals (mass 32:40, mass 44:40, respectively) from the top inlet and the concentration data from the respective sensor (O~2`, CO~2~) was used to calibrate QMS signals to units of Oxygen and CO~2~ concentration. 

After calibration, QMS data from each 450 second inlet period were averaged from second 60 to 420 of the period to allow time for flushing water from the previous inlet from the system and stabilization of the QMS signal. Stepwise linear interpolation was used to combine neighboring high and low inlet periods into 15 minute averages for gradient and flux analysis.

ADV velocity data were separated by data type, then velocity data lines were timestamped using count data and corresponding ADV status data lines, checking for malformed and out-of-sequence rows. A rolling Hampel filter was used to flag extreme outlying points, greater than 8 standard deviations from the running median. Gross range filters were then used to remove physically unreasonable values. After preprocessing, noisy or incoherent velocity data was removed by selecting data with greater than 50% correlation. The velocity time series was completed where possible using linear interpolation where gaps were smaller than 1 s, and consecutive 15 minute blocks were flagged for spectral analysis. Data were also divided into separate periods for each new position of the lander after maintenance to allow rotation of axes to minimize mean vertical current. Cross-power spectral density (CPSD) was used to determine covariance of horizontal and vertical velocity and from that the friction velocity (u-star) term for gradient flux determination. CPSD and u-star were calculated using a vetted procedure in Matlab (Long 2021).

Flux was calculated for each 15 minute block using the gradient method (REF). Flux is estimated using the chemical gradient ($\frac{dO}{dz'}$) and a parameterization of eddy diffusivity (@eq-flux). The eddy diffusivity term ($-K_{DO}$) is in turn parameterized using the friction velocity, turbulent length scale, and von Kármán constant ($\kappa$, taken as 0.4 here, @eq-kdo). The turbulent length scale ($l$) is estimated based on height above the bed surface following McGillis et al. (2011). Continuous estimation of the turbulent length scale was not possible without shear velocity profiles from a co-deployed ADCP. The covariance of the horizontal and vertical current velocity components provided an estimate for the friction velocity ($\mathrm{u*}$) using the root of the CPSD of horizontal and vertical components ($\overline{u'w'}$, @eq-ustar).

$$Flux=-K_{DO}\frac{dO}{dz'}$$ {#eq-flux}

$$K_{DO}=\mathrm{u*}\kappa l$$ {#eq-kdo}

$$\mathrm{u*}=\sqrt{\overline{u'w'}}$$ {#eq-ustar}

Flux was integrated to provide an hourly flux (mmol m^-2^ h^-1^).

# Results

{{< include gems_report_plots.qmd >}}