---
title: "GEMS Flux Report"
format: html
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(targets)
library(dplyr)
library(lubridate)
library(gemstools)
library(ggplot2)
library(plotly)
library(patchwork)
library(here)

# Configure targets to look in parent directory
tar_config_set(store = here("_targets"))

tar_load(rga_adv_flux)
tar_load(hourly_stats)
tar_load(rga_oxygen)
tar_load(seaphox_df_jul)
tar_load(proco2_df_jul)
```

# Flux

```{r}
gop = ggplot(rga_adv_flux, aes(timestamp, ox_flux)) + 
geom_line()

gcp = ggplot(rga_adv_flux, aes(timestamp, co2_flux)) + 
geom_line()

gpp = ggplot(rga_adv_flux, aes(timestamp, par)) + 
geom_line()

gop_ply <- ggplotly(gop, dynamicTicks = TRUE)
gcp_ply <- ggplotly(gcp, dynamicTicks = TRUE)
gpp_ply <- ggplotly(gpp, dynamicTicks = TRUE)

subplot(gop_ply, gcp_ply, gpp_ply, nrows = 3, shareX = TRUE, titleY = TRUE)
```


# Hourly Summary

Daily summary by hour-of-day

```{r}
hmp <- hourly_stats |> 
  ggplot(aes(solar_hour, ox_mean_umol_l_hourly)) +
  geom_line() +
  geom_ribbon(aes(ymin = ox_mean_umol_l_hourly - ox_mean_umol_l_hourly_sd,
                  ymax = ox_mean_umol_l_hourly + ox_mean_umol_l_hourly_sd),
              alpha = 0.2) +
  labs(x = NULL,
       y = "Oxygen Conc. [mmol/m3]")

hgp <- hourly_stats |> 
  ggplot(aes(solar_hour, ox_gradient_umol_l_m_hourly)) +
  geom_line() +
  geom_ribbon(aes(ymin = ox_gradient_umol_l_m_hourly - ox_gradient_umol_l_m_hourly_sd,
                  ymax = ox_gradient_umol_l_m_hourly + ox_gradient_umol_l_m_hourly_sd),
              alpha = 0.2) +
  labs(x = "Hour of Day",
       y = "Oxygen Gradient [mmol/m4]")

flp <- hourly_stats |> 
  ggplot(aes(solar_hour, ox_flux_hourly)) +
  geom_line() +
  geom_ribbon(aes(ymin = ox_flux_hourly - ox_flux_hourly_sd,
                  ymax = ox_flux_hourly + ox_flux_hourly_sd),
              alpha = 0.2) +
  labs(x = "Hour of Day",
       y = "Oxygen Flux [mmol/m2]")

hmp / hgp / flp

# hm_ply <- ggplotly(hmp, dynamicTicks = TRUE)
# hg_ply <- ggplotly(hgp, dynamicTicks = TRUE)
# subplot(hm_ply, hg_ply, nrows = 2, shareX = TRUE, titleY = TRUE)
```

Monthly summary by hour-of-day

# Diagnostic plots

## CO2 flux magnitude issue

Comparison of CO2 and O2 gradient


```{r}
cgp <- hourly_stats |> 
  ggplot(aes(solar_hour, co2_gradient_umol_l_m_hourly)) +
  geom_line() +
  geom_ribbon(aes(ymin = co2_gradient_umol_l_m_hourly - co2_gradient_umol_l_m_hourly_sd,
                  ymax = co2_gradient_umol_l_m_hourly + co2_gradient_umol_l_m_hourly_sd),
              alpha = 0.2) +
  labs(x = "Hour of Day",
       y = "CO2 Gradient [mmol/m4]")

hgp / cgp
```

Compare ProCO2 and RGA


```{r}


co2_df <- proco2_df_jul |>
    select(timestamp = ts, prooceanus_co2_ppm = co2, cell_pressure)
co2_cal_df <- dplyr::inner_join(
    co2_df,
    rga_oxygen,
    by = dplyr::join_by(timestamp)
) |>
    mutate(
        prooceanus_co2_umol_l = co2_ppm_to_umol_per_l(
            xco2_ppm = prooceanus_co2_ppm,
            temp_c = adv_temp, # status temp
            sal_psu = 31.425, # mean seaphox salinity
            pressure_mbar = cell_pressure
        )
    )

co2_model <- lm(
    prooceanus_co2_umol_l ~ mass_44_40_high_mean,
    data = co2_cal_df
)

summary(co2_model)
```


Difference in CO2 is related to PAR/time of day

```{r}
ggplot(co2_cal_df, aes(prooceanus_co2_umol_l, mass_44_40_high_mean, color = par)) +
  geom_point()
```

```{r}
co2_i <- coef(co2_model)[1]
co2_m <- coef(co2_model)[2]

co2_cal_df |>
    mutate(
        co2_high_umol_l = co2_i + co2_m * mass_44_40_high,
        co2_diff = (prooceanus_co2_umol_l - co2_high_umol_l) / prooceanus_co2_umol_l
    ) |>
    ggplot(aes(par, co2_diff, color = adv_temp)) +
    geom_point()
```

pH, O2, CO2

```{r}
co2_min_df <- co2_df |>
  select(timestamp, co2 = prooceanus_co2_ppm) |>
  mutate(timestamp = floor_date(timestamp, unit = "minute")) |>
  group_by(timestamp) |>
    summarize(co2 = mean(co2, na.rm = TRUE))

sp_min_df <- seaphox_df_jul |>
  mutate(timestamp = floor_date(timestamp, unit = "minute")) |>
  group_by(timestamp) |>
    summarize(across(where(is.numeric), \(x) mean(x, na.rm = TRUE)))

sp_co2_df <- left_join(sp_min_df, co2_min_df)
```

No overlap!

```{r}
ggplot(sp_co2_df, aes(timestamp, co2)) +
geom_line()
```

Compare to Ox


```{r}

seaphox_15min <- seaphox_df_jul |>
    mutate(timestamp = lubridate::floor_date(timestamp, "15 minute")) |>
    dplyr::group_by(timestamp) |>
    summarize(across(where(is.numeric), \(x) mean(x, na.rm = TRUE)))

ox_cal_df <- dplyr::left_join(
    seaphox_15min,
    rga_oxygen,
    by = dplyr::join_by(timestamp)
)

ox_model <- lm(seaphox_oxygen_ml_l ~ mass_32_40_high_mean, data = ox_cal_df)
ox_i <- coef(ox_model)[1]
ox_m <- coef(ox_model)[2]

ox_cal_df |>
    mutate(
        oxygen_high = ox_i + ox_m * mass_32_40_high,
        oxygen_low = ox_i + ox_m * mass_32_40_low,
        ox_high_umol_l = o2_ml_l_to_umol_l(oxygen_high, adv_temp)
    )

summary(ox_model)
```

```{r}
ggplot(ox_cal_df, aes(seaphox_oxygen_ml_l, mass_32_40_high_mean, color = par)) +
  geom_point()
```